import type { LegalFolder, LegalSource } from "../drizzle/schema";
import { LEGAL_FORMS_ROOT_FOLDER_ID } from "./db";

const LEGAL_FORM_SOURCE_DEFINITIONS = [
  ["1AEoWr4AY2H2IyDlX1DZXJF4QFo2U6V14", "005دعوى اخلاء عين مؤجرة.doc"],
  ["1FC3LjdLenuqVnhlA2EXdvG2L19Gv4HSx", "1 دعوى بطلان حكم تحكيم.doc"],
  ["1FBO74Crv4SC2s40bkStkIfuZO84KHmfH", "14استئناف حكم اخلاء ايجارات.doc"],
  ["1F5HoHMRXWavPN_4IWfrPyIMjmT9YyEx-", "15طعن ايجارات  ق 4 لسنه 1996.doc"],
  ["1EtfbzLb_oksVQUACPZAq69TX1isaH46K", "18استئناف ايجارات.doc"],
  ["1Esi8XwcQh9HAqNVEbkFhfkjzoACWI8je", "24مذكره_بالرد_على_اسباب_الطعن_بالنقض_ايجارات.doc"],
  ["1EnQYfQM49A-fL8quWGbFbfvNc0Quj3c9", "27مذكرة تحكيم ايجارات.doc"],
  ["1EjSCN0_CCyFiuX0keRgO2ttpIkEejr5q", "28مذكرة تحكيم ايجارات28.doc"],
  ["1EhIMWr_lsDZp0u0RHqVh7X8MZuTOhEYV", "29مذكره ايجارات.doc"],
  ["1EgnuKwlIqCuwZ7KCP7g82V7xJNCRVdPv", "31مذكره ايجارات.doc"],
  ["1EgdV03anL9QvQrZpta4TrX3JJs9zmnGY", "35مذكره_بالرد_على_اسباب_طعن_بالنقض_ايجارات.doc"],
  ["1EOPSwAFr2kT1-dALD8PkO238imA0J6qv", "7مذكرة طعن مدنى ايجارات  الاقامه.doc"],
  ["1EMTROfvPPv5VLgQefYSVrzTHDxm0kZLN", "8مذكره ايجارات.doc"],
  ["1EMErjDgF6H8s9IK0JKRnVOgTDXw4KF6K", "9مذكره_ايجارات_ثبوت_ان_العلاقه_تخضع_لقوانين_ايجار_الاماكن.doc"],
  ["1ELCAoj9kjlgYRIwG93jxmpGnbvj5dfzC", "أشهر_مرافعات_النيابة_العامة_في_القانون_اليمني_تأليف_القاضي_خالد.pdf"],
  ["1E-JodUIf4Z09yuiS9NMFqQfztePy3-gp", "اذن بتسليم.docx"],
  ["1DxsafT8wWjrzIZLJPUo362V6E_3FMU9L", "استئناف_ايجارات_الامتداد_اقانونى_بعد_وفاة_المستأجر_الاصلى.doc"],
  ["1DsHeDqYw-7tQlIwubV0kM3sTdz0A_RrK", "اقراروتنازل_عن_منزل_بصفته_احد_الورثة.doc"],
  ["1Dqa40RWIIQd3hIMGVwjgnidGDN-SCnum", "الإبلاغ-بوقوع-جريمة (1).pdf"],
  ["1DnxUdScM3CcsEz95_ovNZipTTS-QeIma", "التظلم-من-الأوامر-الوقتية.pdf"],
  ["1DmcJbR134wEqks16pPi0nGacEv2uLI7j", "التنفيذ-الجبري-والتنفيذ-المعجل.pdf"],
  ["1DhGNt-FqDJF4XDkmZ5paFFE23ue8qUae", "الصلح-في-الخصومة.pdf"],
  ["1D_ymILjBSPedKxpwW4nPzQJYOlAeU_HV", "الطلب بالامتناع.pdf"],
  ["1DVySfynpU2nZ1nbMHF_VyGt6eI5ByzdQ", "الطلب-بالامتناع.pdf"],
  ["1DPgQKEl-dOmNLyt87giXvPVDGz-peyoH", "ايجارات_من_المقرر_ان_البينة_على_من_ادعى_خلاف_الثابت_اصلا_او_عرضا.doc"],
  ["1DMxT3JRbX7jzQTsV78aeh3qJeVsPDp0Z", "تظلم من أمر الأداء.pdf"],
  ["1DC-_FmiOgyAPJdcjEU3fsX0RPotZi11W", "حق الطريق الخاص.docx"],
  ["1DAwIaOGOl0iVwYJD7r2o01W9csVySoHH", "دعاوى الخطبة وعقود الزواج.pdf"],
  ["1D9mWnav_l2bfuCmOGdrn8kKfGCNooi6G", "دعاوى_إثبات_الربح_أو_طبيعة_المال_عند_الاختلاف.pdf"],
  ["1D82KdPDL7Her1eaN2qRLlX6KV79FLdvn", "دعوى استرداد الحيازة (1).pdf"],
  ["1D7uDwiGVOLzDtWbrVHTL2xD4fuRKHhgS", "دعوى اعتراض-  الدفع.pdf"],
  ["1CqzBd9tWJXseJhKxe9LHmSm7asx3QcDZ", "دعوى الاستحقاق في القانون اليمني.doc"],
  ["1CiZxzo9r0FGXrw1uD9-dcFknDnFQtvVj", "دعوى البطلان (1) (1).pdf"],
  ["1Ccn7VFX4IKS5u2F32LYZ0q-O5Gg_ZoHI", "دعوى التعويض.doc"],
  ["1CUQcBzCYkQhB-kXXud3xM6WcOslGd4JR", "دعوى القايفي.pdf"],
  ["1CLg6zRnVej5cxuDu7HtIrq8Koiq5Hr_8", "دعوى المطالبة بأجر الحارس (العدل).pdf"],
  ["1C7FOPbgnj6Z4SAOoUGa_IwyAhnXcucPa", "دعوى بالحق الشخصي.pdf"],
  ["1C5ssgxCbHkkWJCCQiNpo1_YqOIPAjI3T", "دعوى بحق مدني.doc"],
  ["1C4im-fTuI1sjJlEyxncnhZwDlPmIqB4i", "دعوى شخصية مدنية جنائية مرقمة.pdf"],
  ["1C1c4Fx699HYe3kQQvHgiZeP7ma6L7u0J", "دعوى فسخ احمد الغشم-1.docx"],
  ["1ByWq3j1cx3mrH5V3wk4egYXolN2zOI67", "دعوى مستعجله بطلب انهاء حراسه.doc"],
  ["1BvdCa2TT9xAzxvhMCkEhfkCnADvbZnbM", "دعوى مستعجله لسماع شاهد.doc"],
  ["1BtaO5eKG1NIH5ZbxExXgyv5h1o4AUFCX", "دعوى مستعجله.doc"],
  ["1Bt3DJEed79R4vSQzMI70SGKaUUmuDR-g", "دعوى مطالبة بدين تجاري.doc"],
  ["1BrniySfdsn25nyFRlKAq6lO-dIviW6jp", "دعوى نشوز.doc"],
  ["1BgopGcB-9W24VdeobVHKzlhUOtqJuthz", "دعوى نفقة.doc"],
  ["1JTH4T5KDOA7gWIWH5yzvYEVq5QvsV6pD", "دعوى-بطلان-حكم-محكم.pdf"],
  ["1BeCSGV5TXWoYpmYkwQ4DSV7oOEirG3HK", "دعوى_التعويض_عن_التمييز_في_الخدمات_أو_الأجور_في_حالة_الاحتكار (1).pdf"],
  ["1Bd9dXno0XCegY6f1T6Y682rmjjsubdjy", "دعوى_التعويض_عن_التمييز_في_الخدمات_أو_الأجور_في_حالة_الاحتكار.pdf"],
  ["1BVdI1FF3pZiWrLVUVwrb_Jp6W5jauIsa", "دعوى_المطالبة_باستلام_العمل_أو_اعتبار_العمل_مسلمًا.pdf"],
  ["1BIK3HmbbpuHG-IrD92mbnl8akEmvH0Ye", "دعوى_المطالبة_بالأجر_والنفقات_والتعويض_عند_تلف_الشيء_المقاول_عليه.pdf"],
  ["1B2xUGy1iyzU8rRt723HnBfgotopPHWSv", "دعوى_المطالبة_بالتعويض_عن_فسخ_رب_العمل_للعقد.pdf"],
  ["1B2vng5gyflh1wTruH0lj4d-d_hz1zsPh", "دعوى_المطالبة_بتعويض_ورثة_المقاول_أو_تسليم_المواد_والرسوم.pdf"],
  ["1B2UOWQ3m-9rZH93OJASot4l3B4V0zK95", "دعوى_المطالبة_بتعيين_الحارس_العدل_أو_عزله.pdf"],
  ["1AyjUtA-eMwaltst9UCC9SrN66fVqqB_W", "دعوى_المطالبة_بتعيين_صاحب_الوديعة_أو_قسمتها.pdf"],
  ["1ArsqdGAQ7GO55M-WBaG8WGmLvPWmtomw", "دعوى_المطالبة_برد_الوديعة_أو_قيمتها.pdf"],
  ["1ApgRU_FwgJkcwECeQBvauTrJvmracg_M", "دعوى_المطالبة_بضمان_الحارس_العدل_أو_التعويض_عن_إهماله.pdf"],
  ["1AmctzMOnO5G-UkeNedbMdUugw-pTeefj", "دعوى_المطالبة_بضمان_الفنادق_وما_يماثلها_عن_سرقة_أو_ضياع_أو_تلف_الأشياء.pdf"],
  ["1AlX5PMGoHBDg3a1NyDVdPYsOXxSd_v9Y", "دعوى_المطالبة_بضمان_المتسبب_في_عزل_الوكيل_إذا_تعلق_بالوكالة_حق_للغير.pdf"],
  ["1AhEl9zSQe6VoKB7z6tHjzTk0F6pmcD_j", "دعوى_المطالبة_بضمان_الوديعة_أو_التعويض_عن_تلفها.pdf"],
  ["1AKO2LqTZWZvMVx5c_sCqbOPYJyCUNFKY", "دعوى_المطالبة_بضمان_الوكيل_لما_تلف_أو_ضاع_أو_ما_قبضه_من_ثمن.pdf"],
  ["1AJnqvdLYPbL8USFWET8Ed0lOLikhiQ-M", "دعوى_المطالبة_بمسؤولية_المقاول_الأصلي_عن_عمل_المقاول_من_الباطن.pdf"],
  ["1J_7rb8f7kH7DyTul8dfRe4u-czxxBkmt", "دعوى_مستعجله_باشكال_فى_تنفيذ_حكم_بالتصديق_على_صلح.doc"],
  ["1JMqCJG6wjS1GbjUFnqZJV94P5kD8DpkK", "دعوي_برفع_يد_الغاصب_وإزالة_العدوان_.pdf"],
  ["1JJoorQLVGs-J5UcJPBuwHkLz7Hzx3dI0", "دفع بالجهالة - الحربي.pdf"],
  ["1JHturiQEGUije4gTBDv4zPkuhz9CiVHG", "دفع بالجهالة - العيوي.pdf"],
  ["1J-3gIlkUMFIcWLlj09FXvF6nfkS8GQoz", "دفع بعدم الجريمة.pdf"],
  ["1Is8IhlJviHfMwtkPRNh9NH2WbWIToeAg", "دفع بفوات المدة.pdf"],
  ["1Iq1T9AWuvfp0ZNThnY8t9qUYiBSZpkRV", "دفع قانوني 000.doc"],
  ["1ImRTmXWr4OJ1YZTxurXpqJRXtvNSdfcT", "دفع قانوني.doc"],
  ["1IgWFGYoYtUhrtKOlYCxizy4oGjdZGmR8", "دفوع قانونية.doc"],
  ["1IbfKDNIVTOXUJ0LA-Nx_L_drx3Hatv2g", "رد المدعي.doc"],
  ["1IVbN4wxSZXnxwEBGizYB_Vi2OP1e-UfB", "رد على التقرير الطبي.pdf"],
  ["1IT7guCx-YD1YbZW3oA1tXAK2wHXJYtQC", "رد على الدفع.doc"],
  ["1IKzywLefFwr8T8YNsLlLUnB2UP--9e-h", "رد على الشهود - 2.docx"],
  ["1IJWElXeyWpLhhsY5fUKdpS7ayyzf8996", "رد على طلب.doc"],
  ["1IIBugluR9dti5qqLigHmLENOG_Lwfegz", "رفع_الدعوى_المدنية_التبعية_للدعوى_الجنائية_ممن_لحقه_ضرر_من_الجريمة.pdf"],
  ["1I5DrhPscmhFszU2KWp6jexWGw5YE4nJJ", "سب و قذف.doc"],
  ["1I3uIFsJILXOUQmi1co7GV4dQB24HFXkg", "شكوى_المجني_عليه_كقيد_في_القانون_اليمني.pdf"],
  ["1I344cdcgcotgY5CupQEYFCzWPu3aZdfb", "صحيفة استئناف حكم أحوال شخصية.doc"],
  ["1I2Te6968Z-8HXrikv9GoCIBTyQE2eQ59", "صياغة العقود.docx"],
  ["1I-qmq69DmtymWnn5GH1XAmZScSimgU_A", "صيغ قانونية لبعض العقود.docx"],
  ["1HrUJfqjtwoHYtk61BSLfWc51rM-tCjwr", "صيغة إعلان إنهاء شراكة.doc"],
  ["1HmisqU2o1WK2bfSZmlB3EicyySCDM8sg", "صيغة الدعاوي المستعجلة .pdf"],
  ["1HdVgtnfoyEZ3ZxsUL4D3yJyprbut9WBb", "صيغة تصفية ومخالصة نهائية لمصنع.doc"],
  ["1HWYPnYWvuSE6ZuN1nsATgniIG2y8EjoL", "صيغة توكيل أو تفويض.doc"],
  ["1HLgLSp55CYZbvNdzKzhLbb6PoPbe_KEB", "صيغة توكيل رسمي عام (1).doc"],
  ["1HKy5_2wRJkzD1uDPCJaWvafe3mZrqQD0", "صيغة توكيل رسمي عام.doc"],
  ["1HDKpfL17XFHUoqKggjv8uwAhQWk7ZM0t", "صيغة توكيل شرعي.doc"],
  ["1HAnc6QupoWY63s6_hXnQVKrCKUBCrWQL", "صيغة توكيل لإصدار الترخيص والسجل.doc"],
  ["1H-gJUyeaSpCXjAEUPr6IgLDjCiWS_6j4", "صيغة توكيل.doc"],
  ["1GrQ8ynyiS89z56vAIDC-BXijxCJAXCdo", "صيغة صلح ومخالصة نهائية 1.doc"],
  ["1GclYBrTyMY3i5Ey1pwam6LmfSL8bVeEp", "صيغة صلح ومخالصة نهائية 2.doc"],
  ["1GMKNVQDrun5otJvtV564CQTLy9teNt8Q", "صيغة طلب شطب قضية شيك بدون رصيد (1).doc"],
  ["1GHwe3CREcWhbZNF4TR6RmQAJozTjO5i3", "صيغة طلب شطب قضية شيك بدون رصيد.doc"],
  ["1GBQyEND8E1ilmTOzSKLxARcvrFeNqlHD", "صيغة عرض بإنشاء شركة 1.doc"],
  ["1G33ig-NbXpoG3Mi0Jvuqtgky1REnQDf4", "صيغة عرض بإنشاء شركة 2.doc"],
  ["1G1R5t47pAeurGKc-1OijyYIvypRi6OrL", "صيغة عقد أداء عمل.doc"],
  ["1FsUJ1_Ig99vpmNZWmGTOny9WLzUSjwGP", "صيغة عقد استثمار.doc"],
  ["1FmBHWZSs4yAG60bV0Lb485SoiyUVt7nz", "صيغة عقد بيع أرض زراعية.doc"],
  ["1FZD8yFbSYt2AUJ3vUG7Fb8WBb2GhsaPM", "صيغة عقد بيع حصة شائعة في عقار.doc"],
  ["1FWkQtmigeZgMhrflo4k1zeVzWKMfO6Ke", "صيغة عقد بيع حق الإنتفاع.doc"],
  ["1FSZxU_EcJ_DLqVDLjti58t7osMMPiJqL", "صيغة عقد تقبيل محل تجاري.doc"],
  ["1FLAWsj6tIKgfeXeVXzjDXb4tXG_y-nEx", "صيغة عقد تمثيل.doc"],
  ["1FJvrDX1uXmNK9tyT6vz4IeCd8ztGQBtV", "صيغة عقد شراكـة.doc"],
  ["1FEEFrP8GnG1uYr-pOndJocEaHK87Q0-K", "صيغة عقد صلح.doc"],
  ["1N0mrFHdz_3ig0riV6cRlLm2snUpfdZ1W", "صيغة عقد عمل 1.doc"],
  ["1N0HxhWksRdYLwHG_rhEKe0kZpzBTd5k7", "صيغة عقد عمل 2.doc"],
  ["1N-_rd6rHJ32DiWfNAsXeOS6pnNVqeiUx", "صيغة عقد عمل واستخدام-Arabic-English- (1).doc"],
  ["1Myl2Co49BSQ4jz6zF27W7-cJQNs1oJIl", "صيغة عقد عمل واستخدام-Arabic-English-.doc"],
  ["1MszBiNX6tYCSX8Xh8hkS1q_8i3CgIhXH", "صيغة عقد عمل-Arabic-English-.doc"],
  ["1MqPNFeBy7NLA4R4kpqCzgUixpMTLNgq4", "صيغة عقد قسمة.doc"],
  ["1MRaM9PWSZ4C3Z-dZPyMTn4l8EamGK3XD", "صيغة عقد محاماة 1.doc"],
  ["1MIi4nuxU5dgqLtSfuTwsffqftaZpWHKf", "صيغة عقد محاماة 2.doc"],
  ["1MIgRfHen5TL7h9qvH1cPPeBiZVLHV1uC", "صيغة عقد نقل أشخاص (1).doc"],
  ["1MFrQBZPyMhkMOzCe7Y0u7GvK_YPw0cLs", "صيغة عقد نقل أشخاص.doc"],
  ["1M-uOw_zRY-sOOqaGODYtpCV0WEXeDj2i", "صيغة عقد نقل بضائع.doc"],
  ["1Ly0QfrmUlKtju-rr2VJop9RDiZpaaY58", "صيغة عقد نقل تكنولوجيا.doc"],
  ["1Lw4xrCrpSFl0vilsIYVDVpvier3lpwIO", "صيغة عقد وكالة تجارية 1.doc"],
  ["1Ls2oVImxHU9ZpEz0SW84ZY07x-ttpivZ", "صيغة عقد وكالة تجارية 2.doc"],
  ["1LcyS4iTfq4LYDRazAv35lU9BQewYCTmW", "صيغة عقد وكالة ومحاماة 1.doc"],
  ["1LWg5D0q3xmZRrPLCg8vW7E9Lqy8NSKgB", "صيغة عقد وكالة ومحاماة 2.doc"],
  ["1L04d8fWG0xUr4QvVH4YPCNqovxmckM1g", "صيغة قضية شيك بدون رصيد 1.doc"],
  ["1L-s5G8bpV2kuWXeTMpa4teiybOIQzZGp", "صيغة قضية شيك بدون رصيد 2 (1).doc"],
  ["1Kz_5XGbgcisZpJvhiNiXVYR-4LR97bjo", "صيغة قضية شيك بدون رصيد 2 (2).doc"],
  ["1KyTV_-yVzBgI4wUwocUjfx4wIlbW7xXM", "صيغة قضية شيك بدون رصيد 2.doc"],
  ["1KtJPxVh462yZY3KLm4ez6aTeca69LmcW", "صيغة كفالة.doc"],
  ["1Kk9NOzJqjM4kFxvXGP_Auhd-dRTZRG0S", "صيغة نموذج لصحيفة إشكال من الغير.doc"],
  ["1KhQs3zGmUOeKy_TpmnX8hV0v1_iUbaVl", "صيغة وصية بسهم شائع فى التركة.docx"],
  ["1KeN1-tyUPTfnxJzbq1XnN25vZCmj1fIw", "صيغة وصية عامة لشخص واحد.docx"],
  ["1Kamw1jUn8cxYLh3DBkbNjQn8vOdHvfS7", "صيغة_إقرار_مخالصة_وبراءة_ذمة_english (1).doc"],
  ["1K_endi4XMRJOwSaM_pnlkYfY4WInAR3M", "صيغة_إقرار_مخالصة_وبراءة_ذمة_english (2).doc"],
  ["1KXVmMTS44vN2LNLyEf32pFHqoJyQXsIh", "صيغة_إقرار_مخالصة_وبراءة_ذمة_english.doc"],
  ["1K8DUbkgpJr4QNCVl5-wJw7VyakvXY-Ep", "صيغة_عقد_بيع_حصة_في_التركة_لباقي.doc"],
  ["1K655rhHexyw50JafB3ODhj0FJO-CG04L", "صيغة_وصية_مبتكرة.doc"],
  ["1K0FuUlsjpMWx_ZDO_l-DAe6qHUghdEjg", "صيغه طلب لإستصدار أمر الأداء.doc"],
  ["1JwxAPRYU30VHt3R0GsObpHMAWRw-6srT", "ضمانة على العامل في محل الجملة.docx"],
  ["1Jw-CNmrltkoGRoZX0WIWr5GkPCXIO31h", "طلب أمر الأداء.pdf"],
  ["1JvhK4H-TiZIWiR7cgyDXQpV4nwy5KtlW", "طلب أمر على عريضة.pdf"],
  ["1JugjiHbFgZYfC_Sb5D8oSp39cWshgIxR", "طلب التاجر شهر إفلاس نفسه.pdf"],
  ["1Ju7u-7g2PPyoNDML9G4bNMy_iICu4Edp", "طلب بيع المنقول أو العقار.pdf"],
  ["1Jr7Mg6Nhcdkj9O-Zdonk0F_g5XJwwaqX", "طلب تحريك الدعوى.pdf"],
  ["1JpwhOIHmFhoZ_IsBSMnVoDxbIfNDFaOc", "طلب تصحيح حكم.pdf"],
  ["1Joz28plg7ekQfKcwM3-SGyuwteH-Wtdu", "طلب تغير اسم.doc"],
  ["1JmMPgnQ-23tLpXvCtZWNVZwvIrc59RrC", "طلب تغيير اسم.doc"],
  ["1JlfDOijrxsbTuWsht43xak3XsHAFfIUh", "طلب تقسيم تركة وفرز حصص.doc"],
  ["1JfTOLzT7kfHQBseNB-V4AndsNG2fhQCa", "طلب تقسيم تركة.doc"],
  ["1JdEN6Q1oMG_iD9rb79NFMZePnDrenXs8", "طلب تنفيذ حكم قضائي.pdf"],
  ["1JcoKd4iKcneiU9DpyxgNZvcau8Y5OhIn", "طلب رد القاضي أو عضو النيابة.pdf"],
  ["1Rs5s0Jr0bfDbdt4nC4lKqkQs_-6QBFYf", "طلب رد محكم.pdf"],
  ["1RqkqpM4_20OzsLwY_hD5TDWUTdsXePzO", "طلب عارض.pdf"],
  ["1RoP4w2A2764STH5nXaOg3PZz1DxsVZ_U", "طلب فتح باب المرافعه.doc"],
  ["1RnFtAeNbFQX9AdrKqTEI7olzrbaL2zRC", "طلب فتح مستندى غير قابل للنفض.doc"],
  ["1RZoLA5k-TeD7P2dBXbRcwBVkPmnZLfbI", "طلب منع.docx"],
  ["1QsMFFMARZRk9f11hpmlMNm-51dYbigt9", "طلب-أمر-على-عريضة.pdf"],
  ["1QmmTqwXuMgEpNJ-MeI1JWrDz9n2ZIOtG", "طلب-إشهار-إفلاس-مدين.pdf"],
  ["1QipoY6Qyhnaq-BUpLhy9QLqX_Xg5tGvT", "طلب-إيداع-حكم-تحكيم.pdf"],
  ["1QiBxuoaGhS3Kl5J3m560Qlwnwq7vx717", "طلب-الإدخال-في-الخصومة.pdf"],
  ["1QhfF_QkmSkID3ngzqGYctaXp4dvcFStc", "طلب-التاجر-شهر-إفلاس-نفسه.pdf"],
  ["1QZ4SN-pNCaCKZL5FER4ImH8m1sntjA-V", "طلب-التماس-إعادة-النظر.pdf"],
  ["1QXWtAjSeGdcA6c4Lf00vmQ1B_MvrHkmK", "طلب-بيع-المنقول-أو-العقار.pdf"],
  ["1QXOTu_5Gf5t-89ng-PjHt9Z3qmwqOhX0", "طلب-تحريك-الدعوى.pdf"],
  ["1QT-ZKdFATxFFpy6sM0zeMZ1YkjbCUbGm", "طلب-تدخل.pdf"],
  ["1QJjKWiL-CdldPVn9L3dnGqjqlYJy3OGG", "طلب-تصحيح-حكم.pdf"],
  ["1QJixF0tnQ8kz9KbMOHGcqwowlHA82A4I", "طلب-تعيين-حارس-قضائي.pdf"],
  ["1QGE9rJ9GytMq9OWFtntk8z_6y8CNZIeV", "طلب-تفسير-الحكم.pdf"],
  ["1QEMsthBnYGwuvc4YKq-QUGFPq5ulnIs-", "طلب-تنفيذ-حكم-تحكيم.pdf"],
  ["1Q5zgy5KyJn4aYCHIpbDpmXsZrIvGUyoO", "طلب-تنفيذ-حكم-قضائي.pdf"],
  ["1Q3J3ok3G30Uu0-DgGwP4M9Ao_lwhlJAq", "طلب-رد-محكم.pdf"],
  ["1Q-EW5tI3Ov1qyE623-SCVYfBfAGGIs_6", "طلب-رفع-الدعوى-الجزائية.pdf"],
  ["1RZEO1HYPhU1-O14JIJvM88Frj3hSrjlc", "طلب_رفع_الدعوى_الجزائية_الجنائية_بناءً_على_تقديم_شكوى_1.pdf"],
  ["1RFWjBXdj_M9zzW8eZ5_Dgf6lcDTxLoyv", "طلب_علي_عريضة_لقاضي_الأمور_الوقتية_بالأمر.doc"],
  ["1RPPcHPwOQOXoxUsF8LuX1S9ttqJZWiDP", "طلب_علي_عريضة_لقاضي_الأمور_الوقتية_بالأمر_بتجهيز_ونقل_جثة_عا.doc"],
  ["1Pww7hWqIOJE3nQRR0dKxqj2d7cSDMejK", "طلبات اعالة بعد متوفي.doc"],
  ["1PtBf-Df1lsYwZC5-GVWqzZkGAJNK9x3a", "عبدالسلام عقد بيع.doc"],
  ["1Pj1PL_HfL2_NG9QwDHm9Xs42DzPju-b3", "عبداللطيف.doc"],
  ["1PiM2LsgZLvYKE4xfsQ624T4pC8UFB_m2", "عبدالله مثنى.doc"],
  ["1Pi7HZNX3L2Un_UeCQbbVXBmlOoeQaeNn", "عجز_المدعي_عن_تصحيح_دعواهالمصحح_.docx"],
  ["1PYB6FBLhZjZD_SjkvKVLXkUhjvZVE9tz", "عريضة استصدار امر اداء.doc"],
  ["1PT4eOqmmJZll7ymTN5umbM018pVhNrxK", "عريضة_باستصدار_امر_بالترخيص_للمحضر_بدخول_العقار_للحصول_على_البيانات.doc"],
  ["1PR9Iz59FRMx36wSEogVZDTvrUfCnXRHz", "عقد  بيع بقعة عبدالسلام يحي ياسين.doc"],
  ["1PFhSMGVFXqG7T6gtGzrXkFPaeEuWW2Ph", "عقد إيجار محدد المدة.docx"],
  ["1PASS7_rqYulQHJrBCDqK4VHcMoZaChwb", "عقد اتعاب محامي.docx"],
  ["1P6zJN_bOfWPHzSNGPOX8YwaWYMJw8QyY", "عقد البيع وآثاره.doc"],
  ["1P0sXKm8YuqvFBFqyrgVQuWWt2pE-tEE6", "عقد ايجار.doc"],
  ["1P0lpumbKaAPVL0tL5ZFnOdPuqIfnamb1", "عقد ايجار.pdf"],
  ["1OzPtS3_ZBHe_-MhkW4rGW4YN73rcIgWy", "عقد بيع 111.doc"],
  ["1OuLTugRim7amyW0oh7F53TcUDswe4lO4", "عقد بيع حقوق نشر مطبوعات.doc"],
  ["1Oq7fLXCcIe43cqSbF46K7cxVUpJ7qZkJ", "عقد بيع عبدالقاهر.doc"],
  ["1Om_he9Pcr_236gFpkgGuneaFO5SwIe85", "عقد تعين وكيل بالعمولة.doc"],
  ["1OlSpUFVDS7GMzIjDHznPhzndIw6Ws5VT", "عقد حل شركة.doc"],
  ["1OeQKbHQA_XManKrzXEY0f4oAwCA8eS0S", "عقد شراكة.doc"],
  ["1OeGtNsQAjiHdKzxqCSxNOfWqRn6OIGbb", "عقد عمل بصيدلية.docx"],
  ["1Oe8PhlxJQEdkbo-tLgV8JlwfWAhmxox_", "عقد قسمة رضائية 2.doc"],
  ["1Odqlv6upr0uXYRTJwI-x165kYgx8_TLs", "عقد قسمة رضائية 3.doc"],
  ["1O_dTsNEpPnX8Z7xXX9QsIP-vDx1Sw9hO", "فسخ النكاح لعدم الكفاءه.doc"],
  ["1OXtUjk0AlT3EpV0mvQjwR-ppm0GeZEN2", "لائحة التفتيش القضائي.pdf"],
  ["1OULjYR6rECPR0s5oDqpvqLeWUltFOiaJ", "محمد علي الحاج.docx"],
  ["1OS4NM6s92SDKBGI6k-cqry2QaUQUeiGx", "مشاركة_الزوجة_لزوجها_في_بناء_المنزل.docx"],
  ["1O7CXkZB9TYRWZNmLacprN2HjqcCxZghU", "ملاحظات محضر المعاينة.pdf"],
  ["1NtUEsGJvKl5DvzJO74nqHl0oJiRyrjO_", "مواجهة_الاحتيال_في_قانون_العقوبات_اليمني.pdf"],
  ["1NmWg_dYUmM1BYUDe0u7Zjgi9oPh8q3Ki", "نقض جديد.doc"],
  ["1N__bbTR2PyH2aHG0GlFzD5XbL_Hs7tWx", "نقض جنائي ممتاز.doc"],
  ["1NQ9zxmLhnFaAR10kk3o7b5oibYp9Ah9u", "نماذج ضيغ دعاوي مدنية متنوعة2.docx"],
  ["1NHSVG2sBjTMnFtLeYQ8HYbHQPiCdmnNQ", "نماذج_فارغة_من_طلب_التنفيذوطلب_وضع_الصيغة_التنفيذية_وإعلان_بالسند.pdf"],
  ["1SQnYvZydQwSRVT7J3kymOlC0rwXU8Hui", "نموذج دعوى دين بموجب كمبيالة .pdf"],
  ["1SM6uor8kQIpLbF3CZ0ZXXbtJylO0WSjf", "نموذج دعوى شفعة .doc"],
  ["1SLSpkAjp_gHUCoE8mJ4a7KOY6j-Vw9zz", "نموذج طلب تصدي .docx"],
  ["1SHRBdf2XfQDmII-89zDN8TOEg0WMX97C", "نموذج عقد استشارات .doc"],
  ["1SFIGHdqkg1qKKTETzQTzkDfxw4DJ3x2R", "نموذج عقد تنفيذ مهمة إجرائية.doc"],
  ["1SEUpGB7LZ0IF1fFIxwv1LYuPKGQrQ-zQ", "نموذج_دعوى_بطلب_إخلاء_عين_مؤجرة_لإضرار_المستأجر_بالعين.pdf"],
  ["1SDn3pj8vzKTcldgUgQ0lAkEI9U4YF-w-", "نموذج_طلب_استرداد_الذهب_والمهروالشنطه.doc"],
  ["1S4rOjrKqPMApZp3I5Wsyt4tgo9GveYE2", "نموذج_عقد_محاماة_العميل_مدعى_عليه.doc"],
  ["1S-2Skx74x7q5T1bPg-MmY6UliFhdmh0o", "نموزج دعوى رد شبكه.pdf"],
  ["1Rt7Dkwk1khmRH1jG2WxR9LLmFRriXvfv", "وثيقة عقد طلاق .doc"],
  ["1NNyQP-MmWGbWtn4esXXNTN-ehIulZDsg", "‎⁨نماذج عقود بيوع عقارية⁩.pdf"],
  ["1N4TedAs198gm4-2IiKakg9rwpC3cGwcH", "‎⁨نموذج حكم تحكيم⁩.pdf"],
] as const;

export const legalFormsRootFolder: LegalFolder = {
  id: 0,
  driveFolderId: LEGAL_FORMS_ROOT_FOLDER_ID,
  parentDriveFolderId: null,
  collection: "legal_forms",
  name: "نماذج وصيغ قانونية",
  path: "نماذج وصيغ قانونية",
  sortOrder: 60,
  createdAt: new Date(0),
  updatedAt: new Date(0),
};

export const legalFormSources: readonly LegalSource[] = LEGAL_FORM_SOURCE_DEFINITIONS.map(([driveFileId, title], index) => ({
  id: 910001 + index,
  category: "procedure",
  collection: "legal_forms",
  sortOrder: index + 1,
  driveFileId,
  driveFolderId: LEGAL_FORMS_ROOT_FOLDER_ID,
  folderSortOrder: index + 1,
  title,
  description: `مستورد من مكتبة أ. معين الناصر: نماذج وصيغ قانونية / ${title}`,
  url: `https://drive.google.com/uc?export=download&id=${encodeURIComponent(driveFileId)}`,
  documentType: "other",
  legislationYear: null,
  issuingAuthority: null,
  isFeatured: false,
  createdAt: new Date(0),
  updatedAt: new Date(0),
}));

export function getLegalFormsFolderContents(folderId: string, page: number) {
  if (folderId !== LEGAL_FORMS_ROOT_FOLDER_ID) return { folder: undefined, folders: [], sources: [], totalSources: 0 };
  const safePage = Math.max(1, Math.trunc(page) || 1);
  const start = (safePage - 1) * 7;
  return {
    folder: legalFormsRootFolder,
    folders: [],
    sources: legalFormSources.slice(start, start + 7),
    totalSources: legalFormSources.length,
  };
}

export function getLegalFormSource(sourceId: number): LegalSource | undefined {
  return legalFormSources.find(source => source.id === sourceId);
}
