-- Additional isolated bot state for the Supabase-only Telegram runtime.
-- This migration only creates bot_* tables and never changes platform tables.

create table if not exists public.bot_search_sessions (
  id bigint generated by default as identity primary key,
  chat_id text not null,
  scope text not null check (scope in ('judicial','legislation','all_yemeni_laws','library','contract_templates')),
  query text,
  status text not null default 'awaiting' check (status in ('awaiting','ready')),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists bot_search_sessions_chat_scope_idx on public.bot_search_sessions(chat_id, scope);
create index if not exists bot_search_sessions_expiry_idx on public.bot_search_sessions(expires_at);

create table if not exists public.bot_favorites (
  telegram_user_id text not null,
  source_id bigint not null,
  created_at timestamptz not null default now(),
  primary key (telegram_user_id, source_id)
);

create table if not exists public.bot_user_access (
  telegram_user_id text not null,
  access_scope text not null check (access_scope in ('important_laws','sharia_exams','secondary_exams','managed_menu')),
  managed_menu_item_id bigint,
  approved_by text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (telegram_user_id, access_scope, managed_menu_item_id)
);
create index if not exists bot_user_access_lookup_idx on public.bot_user_access(telegram_user_id, access_scope, expires_at);

create table if not exists public.bot_referrals (
  id bigint generated by default as identity primary key,
  referrer_telegram_user_id text not null,
  referee_telegram_user_id text not null unique,
  referee_chat_id text not null,
  status text not null default 'pending' check (status in ('pending','qualified','rejected')),
  created_at timestamptz not null default now(),
  qualified_at timestamptz,
  rejected_at timestamptz,
  rejection_reason text
);
create index if not exists bot_referrals_referrer_idx on public.bot_referrals(referrer_telegram_user_id, status, created_at desc);

create table if not exists public.bot_referral_rewards (
  id bigint generated by default as identity primary key,
  referrer_telegram_user_id text not null,
  qualified_count integer not null default 0,
  access_scope text not null check (access_scope in ('sharia_exams','secondary_exams')),
  access_starts_at timestamptz not null default now(),
  access_expires_at timestamptz not null,
  status text not null default 'active' check (status in ('active','revoked')),
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  revoke_reason text
);
create index if not exists bot_referral_rewards_lookup_idx on public.bot_referral_rewards(referrer_telegram_user_id, access_scope, status, access_expires_at);

create table if not exists public.bot_subscription_requests (
  id bigint generated by default as identity primary key,
  telegram_user_id text not null,
  chat_id text not null,
  access_scope text not null check (access_scope in ('important_laws','sharia_exams','secondary_exams')),
  managed_menu_item_id bigint,
  telegram_username text,
  telegram_first_name text,
  telegram_last_name text,
  payment_method text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists bot_subscription_requests_pending_idx on public.bot_subscription_requests(status, created_at desc);

create table if not exists public.bot_broadcasts (
  id bigint generated by default as identity primary key,
  owner_telegram_user_id text not null,
  kind text not null check (kind in ('message','document')),
  message text,
  file_id text,
  file_name text,
  caption text,
  status text not null default 'draft' check (status in ('draft','sending','sent','cancelled')),
  recipient_count integer not null default 0,
  success_count integer not null default 0,
  failure_count integer not null default 0,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);
create index if not exists bot_broadcasts_owner_idx on public.bot_broadcasts(owner_telegram_user_id, created_at desc);

create table if not exists public.bot_group_exam_rounds (
  id bigint generated by default as identity primary key,
  chat_id text not null,
  creator_telegram_user_id text,
  subject_key text not null,
  section_key text not null,
  status text not null default 'waiting' check (status in ('waiting','active','completed','cancelled')),
  question_index integer not null default 0,
  time_limit_seconds integer not null default 30,
  active_poll_id text,
  started_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists bot_group_exam_rounds_lookup_idx on public.bot_group_exam_rounds(chat_id, subject_key, section_key, status, updated_at desc);
create index if not exists bot_group_exam_rounds_poll_idx on public.bot_group_exam_rounds(active_poll_id) where active_poll_id is not null;

create table if not exists public.bot_group_exam_participants (
  round_id bigint not null references public.bot_group_exam_rounds(id) on delete cascade,
  telegram_user_id text not null,
  display_name text not null,
  username text,
  score integer not null default 0,
  incorrect_count integer not null default 0,
  missed_count integer not null default 0,
  ready boolean not null default false,
  created_at timestamptz not null default now(),
  primary key (round_id, telegram_user_id)
);

create table if not exists public.bot_group_exam_answers (
  round_id bigint not null references public.bot_group_exam_rounds(id) on delete cascade,
  poll_id text not null,
  telegram_user_id text not null,
  answer char(1) not null check (answer in ('A','B','C','D')),
  created_at timestamptz not null default now(),
  primary key (round_id, poll_id, telegram_user_id)
);

alter table public.bot_search_sessions enable row level security;
alter table public.bot_favorites enable row level security;
alter table public.bot_user_access enable row level security;
alter table public.bot_referrals enable row level security;
alter table public.bot_referral_rewards enable row level security;
alter table public.bot_subscription_requests enable row level security;
alter table public.bot_broadcasts enable row level security;
alter table public.bot_group_exam_rounds enable row level security;
alter table public.bot_group_exam_participants enable row level security;
alter table public.bot_group_exam_answers enable row level security;
