create table if not exists public.bot_managed_menu_items (
  id bigint generated by default as identity primary key,
  label text not null,
  action_type text not null check (action_type in ('url','message','file')),
  action_value text not null,
  row_index integer not null default 0,
  sort_order integer not null default 0,
  access_mode text not null default 'free' check (access_mode in ('free','premium','hasad')),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.bot_managed_sections (
  section_key text primary key,
  display_label text not null,
  enabled boolean not null default true,
  access_mode text not null default 'premium' check (access_mode in ('subscription','free','premium','hasad')),
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);
create table if not exists public.bot_managed_messages (
  message_key text primary key,
  content text not null,
  updated_at timestamptz not null default now()
);
create table if not exists public.bot_admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id text not null,
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists bot_admin_audit_logs_created_idx on public.bot_admin_audit_logs(created_at desc);
alter table public.bot_managed_menu_items enable row level security;
alter table public.bot_managed_sections enable row level security;
alter table public.bot_managed_messages enable row level security;
alter table public.bot_admin_audit_logs enable row level security;
