-- Bot runtime storage for the Supabase-only Vercel deployment.
-- This migration is isolated from the platform tables and does not alter or delete existing data.

create table if not exists public.bot_subscribers (
  chat_id text primary key,
  telegram_user_id text not null,
  telegram_username text,
  telegram_first_name text,
  telegram_last_name text,
  subscribed_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index if not exists bot_subscribers_user_idx on public.bot_subscribers (telegram_user_id);

create table if not exists public.bot_platform_access (
  telegram_user_id text primary key,
  confirmed_at timestamptz not null default now(),
  web_app_verified_at timestamptz,
  region text
);

create table if not exists public.bot_hasad_access (
  telegram_user_id text primary key,
  visited_at timestamptz not null default now(),
  region text
);

create table if not exists public.bot_exam_forms (
  id bigint generated by default as identity primary key,
  subject_key text not null,
  form_key text not null,
  form_name text not null,
  sort_order integer not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (subject_key, form_key)
);

create index if not exists bot_exam_forms_subject_idx on public.bot_exam_forms (subject_key, is_active, sort_order, id);

create table if not exists public.bot_exam_questions (
  id bigint generated by default as identity primary key,
  source_question_id text not null unique,
  subject_key text not null,
  section_key text not null,
  question_text text not null,
  option_a text not null default '',
  option_b text not null default '',
  option_c text not null default '',
  option_d text not null default '',
  correct_option char(1) not null check (correct_option in ('A', 'B', 'C', 'D')),
  explanation text not null default '',
  hint text,
  sort_order integer not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bot_exam_questions_section_idx on public.bot_exam_questions (subject_key, section_key, is_active, sort_order, id);

create table if not exists public.bot_exam_sessions (
  id bigint generated by default as identity primary key,
  telegram_user_id text not null,
  chat_id text not null,
  subject_key text not null,
  section_key text not null,
  status text not null default 'active' check (status in ('active', 'completed', 'cancelled')),
  question_index integer not null default 0,
  score integer not null default 0,
  incorrect_count integer not null default 0,
  missed_count integer not null default 0,
  time_limit_seconds integer not null default 30,
  active_poll_id text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists bot_exam_sessions_user_idx on public.bot_exam_sessions (telegram_user_id, status, updated_at desc);
create index if not exists bot_exam_sessions_poll_idx on public.bot_exam_sessions (active_poll_id) where active_poll_id is not null;

create table if not exists public.bot_exam_results (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.bot_exam_sessions(id) on delete cascade,
  telegram_user_id text not null,
  subject_key text not null,
  section_key text not null,
  score integer not null default 0,
  incorrect_count integer not null default 0,
  missed_count integer not null default 0,
  elapsed_seconds integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists bot_exam_results_leaderboard_idx on public.bot_exam_results (subject_key, section_key, score desc, elapsed_seconds asc, created_at asc);

create table if not exists public.bot_usage_events (
  id bigint generated by default as identity primary key,
  telegram_user_id text not null,
  event_type text not null check (event_type in ('browse', 'search', 'document_request', 'support_request')),
  section_key text,
  query text,
  source_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.bot_support_requests (
  id bigint generated by default as identity primary key,
  telegram_user_id text not null,
  chat_id text not null,
  message text not null,
  status text not null default 'new' check (status in ('new', 'reviewed')),
  created_at timestamptz not null default now()
);

alter table public.bot_subscribers enable row level security;
alter table public.bot_platform_access enable row level security;
alter table public.bot_hasad_access enable row level security;
alter table public.bot_exam_forms enable row level security;
alter table public.bot_exam_questions enable row level security;
alter table public.bot_exam_sessions enable row level security;
alter table public.bot_exam_results enable row level security;
alter table public.bot_usage_events enable row level security;
alter table public.bot_support_requests enable row level security;
